In [3]:
import pandas as pd

In [8]:
df = pd.read_csv("mods.txt", sep=',')

In [9]:
df.head()

,#Mod_Priority,#Mod_Status,#Mod_Name,#Note,#Mod_Nexus_URL,#Download_File_Name
0,0,+,DLC: HearthFires,NaN,NaN,NaN
1,1,+,DLC: Dragonborn,NaN,NaN,NaN
2,2,+,DLC: Dawnguard,NaN,NaN,NaN
3,3,+,Creation Club: ccQDRSSE001-SurvivalMode,NaN,NaN,NaN
4,4,+,Creation Club: ccBGSSSE037-Curios,NaN,NaN,NaN

In [21]:
df.drop(["#Mod_Status", "#Note", "#Download_File_Name", "#Mod_Priority"], axis = 1)

,#Mod_Name,#Mod_Nexus_URL
0,DLC: HearthFires,NaN
1,DLC: Dragonborn,NaN
2,DLC: Dawnguard,NaN
3,Creation Club: ccQDRSSE001-SurvivalMode,NaN
4,Creation Club: ccBGSSSE037-Curios,NaN
...,...,...
529,Paarthurnax - Quest Expansion Dublagem PT BR,https://www.nexusmods.com/skyrimspecialedition...
530,DUBLAGEM 1.6 + FIXES,https://www.nexusmods.com/skyrimspecialedition...
531,DBVO Victoria - Feminino - ESCOLHA APENAS OQUE...,https://www.nexusmods.com/skyrimspecialedition...
532,DBVO sylas - Masculino - ESCOLHA APENAS OQUE V...,https://www.nexusmods.com/skyrimspecialedition...
533,FRESH INSTALL_separator,NaN

In [22]:
import streamlit as st

In [24]:
st.title("Mods Skyrim")
st.dataframe(df)

2026-02-26 08:15:32.723 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-02-26 08:15:32.723 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-02-26 08:15:32.724 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-02-26 08:15:32.725 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-02-26 08:15:32.726 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-02-26 08:15:32.726 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [27]:
from IPython.display import display
display(df)

,#Mod_Priority,#Mod_Status,#Mod_Name,#Note,#Mod_Nexus_URL,#Download_File_Name
0,0,+,DLC: HearthFires,NaN,NaN,NaN
1,1,+,DLC: Dragonborn,NaN,NaN,NaN
2,2,+,DLC: Dawnguard,NaN,NaN,NaN
3,3,+,Creation Club: ccQDRSSE001-SurvivalMode,NaN,NaN,NaN
4,4,+,Creation Club: ccBGSSSE037-Curios,NaN,NaN,NaN
...,...,...,...,...,...,...
529,529,+,Paarthurnax - Quest Expansion Dublagem PT BR,NaN,https://www.nexusmods.com/skyrimspecialedition...,C:/Users/Leandro/Downloads/Paarthurnax - Quest...
530,530,+,DUBLAGEM 1.6 + FIXES,NaN,https://www.nexusmods.com/skyrimspecialedition...,C:/Users/Leandro/Downloads/sound.zip-105861-1-...
531,531,-,DBVO Victoria - Feminino - ESCOLHA APENAS OQUE...,NaN,https://www.nexusmods.com/skyrimspecialedition...,C:/Users/Leandro/Downloads/Victoria - Feminino...
532,532,-,DBVO sylas - Masculino - ESCOLHA APENAS OQUE V...,NaN,https://www.nexusmods.com/skyrimspecialedition...,C:/Users/Leandro/Downloads/Sylas - Masculino-1...
533,533,-,FRESH INSTALL_separator,NaN,NaN,NaN